from setuptools import setup, find_packages

setup(
    name='omnipytron-neural-converter',
    version='0.1',
    packages=find_packages(),
    install_requires=[
        'tensorflow',
        'numpy',
        'flask',
        'scipy',
        'scikit-learn',
        'PyPDF2',
        'pdfminer.six',
        'pandas',
        'nltk',
        'gensim',
        'spacy',
        'transformers',
        'torch',
        'onnx',
        'serpapi',
        'statsmodels',
        'prophet',
        'matplotlib',
        'pytesseract',
        'Pillow',
    ],
    author='Your Name',
    author_email='your.email@example.com',
    description='A comprehensive tool for neural network operations and data processing',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/yourusername/omnipytron-neural-converter',
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.6',
)
